name: Build macOS Application

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest # 使用最新的 macOS 环境

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Rust Toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable

    - name: Install Dependencies (Homebrew & Cargo)
      run: |
        # GitHub Actions 的 macOS runner 自带 Homebrew
        echo "Installing OpenCV..."
        brew install opencv
        
        echo "Installing cargo-bundle..."
        cargo install cargo-bundle

    - name: Make Packaging Script Executable
      run: chmod +x package_macos.sh # 给予我们的打包脚本执行权限

    - name: Run Packaging Script
      # 这里直接执行我们之前编写好的脚本，完成所有核心打包工作
      run: ./package_macos.sh

    - name: Archive the Application
      id: archive_app
      run: |
        APP_NAME="Polarimeter"
        
        ARTIFACT_NAME="${APP_NAME}-macos-v${{ github.run_number }}.zip"
        
        echo "Archiving $APP_NAME.app to $ARTIFACT_NAME..."
        cd target/release/bundle/osx/
        zip -r "../../../${ARTIFACT_NAME}" "${APP_NAME}.app"
        cd ../../../..

        echo "artifact_name=${ARTIFACT_NAME}" >> $GITHUB_OUTPUT
      # shell: pwsh # 在 macOS runner 上也可以使用 PowerShell 来统一脚本语言

    - name: Upload Artifact (zip)
      uses: actions/upload-artifact@v4
      with:
        name: polarimeter-macos-package
        # 使用上一步生成的压缩包的完整路径
        path: target/${{ steps.archive_app.outputs.artifact_name }}